### ISSUE TITLE
./build.sh and ./runContainer.sh dont exist

### ISSUE THREAD

**Issue by guysoft** [floge77/cloud2podcast#3]
hey,
Trying to get this to work, but the README does not match at all the current codebase.

I managed as far as building the docker container and starting it, but then I get:

cloudtopodcast    | 2019/05/20 13:31:54 Could not open /downloads/config.yaml Error: open /downloads/config.yaml

Perhaps you need a working docker-compose example?

**Comment by floge77** [comment]
Hey guysoft,

nice that you found the repo.
I coded that stuff a while back as my first experience with coding in Go.
I am honest I need to invest some hours at the weekend and try to get it working again (I will notice you then).

**Comment by floge77** [comment]
Sooooo I spent now about 2 hours refactoring my stuff (would not code it like this again :-D ) and now it is working again. I also had to overwrite the history because of some hardcoded paths of my machine which should not be on github ;-)
The app has still some hard assumptions like the directory tree or the naming of the files which will be downloaded.
But anyway you can now try using the app and if it doesn't work feel free contacting me again.

**Comment by floge77** [comment]
If everything is ok just ping me and I'll close the issue

**Comment by guysoft** [comment]
Ok, I can build and serve it. The page gives though ``404 page not found`` on root ``/``.

Also you have to place a config.yaml in the downloads folder.

**Comment by floge77** [comment]
I pushed a new commit with enhanced documentation and changed the mounted directory.
Just download some tracks with youtube-dl into the downloads-directory/youtube/Channelname. This Channelname has to be identical with the channelname from the config.yaml.
When running the docker container ensure that you are at the root direcotry of the repositpry

**Comment by guysoft** [comment]
Hey, I kinda lost interest, sorry other pressing things. If you want to close this issue you can.
Sorry :-/
